name:                FP-Softwareprojekt
version:             0.1.0.0
github:              "BB20101997/FP-Softwareprojekt"
license:             MIT
author:              "Bennet Bleßmann, Sven Korfmann"
maintainer:          "bennet-blessmann@t-online.de"
copyright:           "2018 Bennet Bleßmann, Sven Korfmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/BB20101997/FP-Softwareprojekt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  FP-Softwareprojekt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FP-Softwareprojekt

tests:
  FP-Softwareprojekt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FP-Softwareprojekt
    - QuickCheck
